/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author rafaela.armiliato
 */
public class ListagemMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListagemMateria
     */
    public ListagemMateria() {
        this("", "");
    }

    /**
     * Cria a listagem já filtrada pelo intervalo de códigos informado na tela
     * de opções do relatório. Intervalo vazio lista todas as matérias primas.
     */
    public ListagemMateria(String codigoDe, String codigoAte) {
        initComponents();
        carregarTabela(codigoDe, codigoAte);
    }

    /**
     * Busca as matérias primas e preenche a tabela aplicando o filtro.
     */
    private void carregarTabela(String codigoDe, String codigoAte) {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new String[]{"Registro", "Código", "Produto", "Unidade", "Custo", "Reposição"}, 0) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        };
        dao.DataSource dataSource = new dao.DataSource();
        try {
            for (model.MateriaPrima materia : new dao.MateriaPrimaDAO(dataSource).listarTodos()) {
                if (dentroDoIntervalo(materia.getCodigo(), codigoDe, codigoAte)) {
                    modelo.addRow(new Object[]{
                        materia.getId(),
                        materia.getCodigo(),
                        materia.getNome(),
                        materia.getUnidade(),
                        materia.getCustoReposicao(),
                        materia.getQuantidadeEstoque()
                    });
                }
            }
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao carregar a listagem: " + ex.getMessage(),
                    "Listagem de matéria prima", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            dataSource.CloseDataSource();
        }
        jTable1.setModel(modelo);
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Nenhuma matéria prima encontrada para o filtro informado.",
                    "Listagem de matéria prima", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean dentroDoIntervalo(String codigo, String codigoDe, String codigoAte) {
        if (codigoDe == null || codigoDe.isEmpty() || codigoAte == null || codigoAte.isEmpty()) {
            return true;
        }
        if (codigo == null) {
            return false;
        }
        return codigo.compareToIgnoreCase(codigoDe) >= 0
                && codigo.compareToIgnoreCase(codigoAte) <= 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listagem de matéria prima");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Registro", "Código", "Produto", "Unidade", "Custo", "Reposição"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listagem de matéria prima");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
